# Generated by Django 5.2.17 on 2026-08-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="menu_items/"),
        ),
    ]
